name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - run: pnpm run zip
      - uses: actions/upload-artifact@v4
        with:
          name: 283pip-artifact-${{ github.sha }}
          path: .output/**/*.zip
